apiVersion: v1
kind: DeploymentConfig
metadata:
  name: backend-worker-03
spec:
  replicas: 0
  selector:
    name: backend-worker-03
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        name: backend-worker-03
    spec:
      containers:
      - args:
        - 3scale_backend_worker
        - run
        env:
        - name: CONFIG_REDIS_PROXY
          value: backend-redis:6379
        - name: CONFIG_QUEUES_MASTER_NAME
          value: backend-redis:6379/1
        - name: RACK_ENV
          value: production
        - name: CONFIG_EVENTS_HOOK
          value: http://system-provider:3000/master/events/import
        - name: CONFIG_EVENTS_HOOK_SHARED_SECRET
          value: aucn1fuc
        - name: CONFIG_REDISCACHE_URL
          value: redis-cache-service-03:6379
        image: quay.io/3scale/backend:v2.2.0-ER2-nodecache
        imagePullPolicy: IfNotPresent
        name: backend-worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-102-111.eu-central-1.compute.internal
      imagePullSecrets:
        - name: 3scale-redhat-pull-secret
  test: false
  triggers:
  - type: ConfigChange
