apiVersion: v1
kind: Service
metadata:
  name: backend-listener
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: backend-listener
  sessionAffinity: None
  type: ClusterIP
