apiVersion: v1
data:
  redis.conf: |
    protected-mode no
    port 6379
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    loglevel notice
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    appendonly no
    dir /var/lib/redis/data
kind: ConfigMap
metadata:
  name: redis-cache-config
