apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service-01
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-cache-01
  sessionAffinity: None
  type: ClusterIP
